# sed script file for converting a mode generated by Xtext to be importable the education platform 

1 i\import {define} from "ace-builds";\n\n 
s@define(@&'ace/mode/xtext-LANGUAGE_EXT', @
s@function(oop, mText, mTextHighlightRules) {\n@&        "use strict";\n\n 	//oop, mText, mTextHighlightRules\n	var oop = require("../lib/oop");\n	var mText  = require("./text");\n	var mTextHighlightRules = require("./text_highlight_rules");\n\n@
s@function(oop, mText, mTextHighlightRules)@function(require,exports,module)@
s@"xtext/\(.*\)";@"ace/mode/xtext-LANGUAGE_EXT";@
s@return {\n		Mode: Mode\n	};@exports.Mode=Mode;@

